const profileTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILES: 'GET_PROFILES',
    PROFILE_ERROR: 'PROFILE_ERROR',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    GET_REPOS: 'GET_REPOS'
}

export default profileTypes;