const authTypes = {
    REGISTER_SUCCESS : 'REGISTER_FAIL',
    REGISTER_FAIL :'REMOVE_ALERT',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL' 
}

export default authTypes;